return {
    ['open_menu'] = 'Pressione ~INPUT_CONTEXT~ para jogar ~p~HighOrLow~w~',
    ['highorlow'] = 'A próxima carta será maior ou menor?',
    ['higher'] = 'Maior',
    ['lower'] = 'Menor',
    ['currentlycard'] = 'Carta aberta: ',
    ['howmuch'] = 'Quanto você quer apostar?',
    ['won'] = '~g~Você ganhou!~w~\nA próxima carta é ',
    ['lost'] = '~p~Você perdeu!~w~\nA carta sorteada é ',
    ['nomoney'] = "~p~Jogo cancelado\n~w~Você não tem dinheiro suficiente para jogar.",
    ['Clubs'] = 'Paus',
    ['Spades'] = 'Espadas',
    ['Hearts'] = 'Copas',
    ['Diamonds'] = 'Ouros',
    ['Jack'] = 'Valete',
    ['Queen'] = 'Rainha',
    ['King'] = 'Rei',
    ['Ace'] = 'Ás',
}
