['de'] = {
	['open_menu'] = 'Drücke ~INPUT_CONTEXT~ um ~p~HighOrLow ~w~zu spielen',
	['highorlow'] = 'Ist die nächste Karte höher oder tiefer?',
	['higher'] = 'Höher',
	['lower'] = 'Niedriger',
	['currentlycard'] = 'Offene Karte: ',
	['howmuch'] = 'Wie viel möchtest Du setzen?',
	['won'] = '~g~Du hast gewonnen!~w~\nDie nächste Karte ist ',
	['lost'] = '~p~Du hast verloren!~w~\nDie gezogene Karte ist ',
	['nomoney'] = '~p~Spiel abgebrochen\n~w~Du hast nicht genug Geld um zu spielen.',
},
