return {
    ['open_menu'] = 'Naciśnij ~INPUT_CONTEXT~, aby zagrać w ~p~HighOrLow~w~',
    ['highorlow'] = 'Czy następna karta będzie wyższa czy niższa?',
    ['higher'] = 'Wyższa',
    ['lower'] = 'Niższa',
    ['currentlycard'] = 'Otwarta karta: ',
    ['howmuch'] = 'Ile chcesz postawić?',
    ['won'] = '~g~Wygrałeś!~w~\nNastępna karta to ',
    ['lost'] = '~p~Przegrałeś!~w~\nWylosowana karta to ',
    ['nomoney'] = "~p~Gra przerwana\n~w~Nie masz wystarczająco pieniędzy, aby grać.",
    ['Clubs'] = 'Trefl',
    ['Spades'] = 'Pik',
    ['Hearts'] = 'Kier',
    ['Diamonds'] = 'Karo',
    ['Jack'] = 'Walet',
    ['Queen'] = 'Dama',
    ['King'] = 'Król',
    ['Ace'] = 'As',
}