return {
	['open_menu'] = 'Press ~INPUT_CONTEXT~ to play ~p~HighOrLow~w~',
    ['highorlow'] = 'Is the next card higher or lower?',
    ['higher'] = 'Higher',
    ['lower'] = 'Lower',
    ['currentlycard'] = 'Open card: ',
    ['howmuch'] = 'How much would you like to bet?',
    ['won'] = '~g~You have won!~w~\nThe next card is ',
    ['lost'] = '~p~You have lost!~w~\nThe drawn card is ',
    ['nomoney'] = '~p~Game canceled\n~w~You do not have enough money to play.',
	['Clubs'] = 'Clubs',
	['Spades'] = 'Spades',
	['Hearts'] = 'Hearts',
	['Diamonds'] = 'Diamonds',
	['Jack'] = 'Jack',
	['Queen'] = 'Queen',
	['King'] = 'King',
	['Ace'] = 'Ace',
}
