return {
    ['open_menu'] = 'Tryck på ~INPUT_CONTEXT~ för att spela ~p~HighOrLow~w~',
    ['highorlow'] = 'Blir nästa kort högre eller lägre?',
    ['higher'] = 'Högre',
    ['lower'] = 'Lägre',
    ['currentlycard'] = 'Öppet kort: ',
    ['howmuch'] = 'Hur mycket vill du satsa?',
    ['won'] = '~g~Du vann!~w~\nNästa kort är ',
    ['lost'] = '~p~Du förlorade!~w~\nDet dragna kortet är ',
    ['nomoney'] = "~p~Spelet avbröts\n~w~Du har inte tillräckligt med pengar för att spela.",
    ['Clubs'] = 'Klöver',
    ['Spades'] = 'Spader',
    ['Hearts'] = 'Hjärter',
    ['Diamonds'] = 'Ruter',
    ['Jack'] = 'Knekt',
    ['Queen'] = 'Dam',
    ['King'] = 'Kung',
    ['Ace'] = 'Ess',
}
