['en'] = {
  ['open_menu'] = 'Drücke ~INPUT_CONTEXT~ um deinen Dienststatus zu verwalten',
  ['status'] = 'Dienststatus',
  ['status_disc'] = 'Gehe in/aus den Dienst',
  ['duty'] = 'Statusverwaltung',
  ['duty_disc'] = 'Gehe in & aus den Dienst',
  ['offduty_msg'] = '~p~Du befindest dich nun außerdienst, schönen Feierabend!.',
  ['onduty_msg_01'] = '~p~Du befindest dich nun im Dienst.',
  ['onduty_msg_02'] = '~p~Du befindest dich nun im Polizeidienst.',
  ['duty_failed'] = '~r~Du bist nicht dazu berechtigt den Dienststatus zu wechseln.',
},
