['de'] = {
        ['open_menu'] = 'Drücke ~INPUT_PICKUP~ um auf den ATM zuzugreifen',
		['open_menu2'] = 'Drücke ~INPUT_PICKUP~ um dein Bankkonto zu verwalten',
		--- HAUPTMENU
		['atm'] = 'Fleeca',
		['atm_subtitle'] = 'Fleecabanking',
		['withdraw'] = 'Abheben',
	    ['deposit'] = 'Einzahlen',
		['billings'] = '~b~Rechnungen',
		['billings_disc'] = 'Eingegangende Rechnungen',
		--------------------------------------
		['money_in_cash'] = '~g~Bargeld',
		['money_in_bank'] = '~o~Kontostand',
		----------------------------------------
		['rob'] = '~r~Ausrauben',
		['rob2'] = 'Ausrauben',
		['rob_disc'] = '~r~Raube den ATM aus!',
		['rob_disc_item'] = '~o~Sind Sie sicher, dass Sie dies tun wollen?',
		['stop'] = '~r~Abbrechen',
		['yes'] = '~g~Ja',
		['error'] = 'Fehler',
		['atm_blip'] = 'Fleecabank',
		----------------------------------------
		['withdraw_disc'] = 'Heben Sie Geld Ihrem Konto ab',
		['withdraw_disc_info_item'] = 'Geld auszahlen lassen:',
		['withdraw_custom_item'] = '~g~Eigene Auszahlung',
		['withdraw_custom_box'] = 'Wie viel möchten Sie abheben?',
		['deposit_disc'] = 'Zahlen Sie Geld auf Ihr Konto ein',
		['deposit_disc_info_item'] = 'Geld einzuzahlen:',
		['deposit_custom_item'] = '~g~Eigene Einzahlung',
		['deposit_custom_box'] = 'Wie viel möchten Sie einzahlen?',
		['login'] = 'Einloggen',
		['logout'] = 'Ausloggen',
		['login_disc'] = 'Greifen Sie auf den ~b~ATM~w~ zu!',
		['logout_disc'] = 'Melden Sie sich aus dem ~b~ATM~w~ aus!',
		-----
		['atm1'] = '~g~100$',
		['atm2'] = '~g~500$',
		['atm3'] = '~g~1 000$',
		['atm4'] = '~g~10 000$',
		-----
		['bank_notify_1'] = 'Es wurden ~g~%s$~s~ von deinem Konto abgehoben',
		['bank_notify_2'] = 'Es können ~r~keine %s$~w~ abgehoben werden, wenn Sie diese nicht besitzen!',
		['bank_notify_3'] = 'Es wurden ~g~%s$~s~ auf deinem Konto eingezahlt',
		['bank_notify_4'] = 'Es können ~r~keine %s$~w~ eingezahlt werden, wenn Sie diese nicht besitzen!',
		----
		['welcome'] = '~b~Willkommen zurück!',
		['welcome_player'] = 'Herzlich willkommen zurück, ~b~%s~w~! Ihre Fleeca Bank LS steht Ihnen jederzeit zur Seite!',
		---- NEU in V2 ----
		['robbery_notify1'] = '~r~Du fängst an dich am Automaten zu schaffen zu machen...~w~',
		['robbery_notify2'] = 'Das Display lässt sich jetzt lösen, mach lieber schnell!',
		['robbery_notify3'] = '~r~Die Geldkassette konnte aufgebrochen werden... Die Cops wurden verständigt...',
		['robbery_notify4'] = '~r~Du ziehst die erste Geldkassette raus...~w~',
		['robbery_notify5'] = 'Du siehst die Bündel und fängst an diese einzupacken!',
		['robbery_notify6'] = 'Das waren ~g~$%s~w~!',
		['robbery_notify7'] = 'Das waren weitere ~g~$%s~w~!',
		['robbery_notify8'] = 'Das waren wieder ~g~$%s~w~! Jetzt ist der Automat leer, lauf!',
		----
		['police_notify'] = 'Ein Geldautomat meldet eine Störung oder einen gewaltsames Eindringen!',
		['robbery_notenough'] = 'Es sind nicht genug Polizisten im Dienst.',
		--- NEU in 2.1
		['transfer'] = 'Überweisung',
		['transfer_menu_but'] = '~o~Überweisung',
		['transfer_disc'] = 'Tätige eine Überweisung an einen anderen Spieler.',
		['tranfer_button'] = '~g~Überweisung tätigen',
		['daily_costs_title'] = 'Kontoführungsgebühr',
		['daily_costs_msg'] = 'Dir wurden ~r~$%s~w~ abgezogen.',
		['daily_costs_msg_failed'] = '~r~Du konntest dir die Kontoführungsgebüren nicht leisten',
		['transfer_failed_self'] = '~r~Du kannst dir nicht selber Geld überweisen.',
		['transfer_failed_too_much'] = '~r~Du kannst nicht soviel überweisen, wenn du es nicht besitzt.',
		['transfer_success'] = 'Du überweist ~r~$ %s~s~ an ~r~%s.',
		['transfer_received'] = 'Du erhälst eine Überweisung in Höhe von ~g~$ %s~s~ durch ~g~%s.',
		['transfer_who_received'] = 'Wie lautet die IBAN des Empfängers?',
		['transfer_amount'] = 'Wie viel möchten Sie überweisen?',
		['atm_rob_police_title'] = 'Geldautomatenwarnung',
		['atm_rob_police_disc'] = 'ATM Security System',
		['atm_rob_police_msg'] = 'Ein Geldautomat meldet verdächtige Aktivitäten.',
		['atm_rob_police_blip'] = 'Geldautomat - Einsatzort',
		--- advancedblips
		['times1_blip'] = 'Öffnungszeiten',
		['times2_blip'] = '5:00 - 22:30 Uhr',
		['withdraw_blip'] = 'Bargeldauszahlung',
		['yes_blip'] = 'Ja',
		['sendmoney_blip'] = 'Überweisungen',
		['employees_blip'] = 'Mitarbeiter',
		['employees_amount_blip'] = '1-2',
		['place_blip'] = 'Ort',
		['place2_blip'] = 'öffentliche Bank',
		['disc_blip'] = 'Deine Fleecabank Los Santos steht Dir jederzeit zur Seite. Deportiere sicher Dein Geld & profitiere von zahlreichen Vorteilen!',
		----
		--- advancedblips
		['times1_blip'] = 'Öffnungszeiten',
		['times2_blip'] = '5:00 - 22:30 Uhr',
		['withdraw_blip'] = 'Bargeldauszahlung',
		['yes_blip'] = 'Ja',
		['sendmoney_blip'] = 'Überweisungen',
		['employees_blip'] = 'Mitarbeiter',
		['employees_amount_blip'] = '1-2',
		['place_blip'] = 'Ort',
		['place2_blip'] = 'öffentliche Bank',
		['disc_blip'] = 'Deine Fleecabank Los Santos steht Dir jederzeit zur Seite. Deportiere sicher Dein Geld & profitiere von zahlreichen Vorteilen!',
		---- update
		['transactions_info'] = 'Transaktionen',
		['payback_message'] = 'Du hast noch einen ausstehenden Kredit von ~r~$%s~s~. Zahle ihn bitte zurück.',
		['payback_successfully'] = 'Du hast den Kredit vollständig zurückgezahlt.',
		['payback_not_money'] = 'Du musst den vollen Betrag von ~g~$50,000~s~ zurückzahlen.',
		['payback_failed'] = 'Du musst den vollen Betrag von ~g~$50,000~s~ zurückzahlen.',
		['takecredit_failed'] = 'Du hast bereits einen laufenden Kredit bei dieser Bank. Zahle ihn ab um einen neuen aufzunehmen.',
		['takecredit_success'] = 'Du hast einen Kredit von ~g~$50,000~s~ aufgenommen.',
		['credit_info'] = 'Credit: 50.000$',
		['paycredit_info'] = '~p~Kredit abbezahlen',
		['takecredit_info'] = '~p~Kredit nehmen',
		['credit'] = 'Kredit',
		['credit2'] = 'Nehme einen Kredit auf',
		['insertcard'] = 'Kreditkarte wird eingesteckt.',

    },
