['en'] = {
        ['open_menu'] = 'Press ~INPUT_PICKUP~ to access the ATM',
		--- MAINMENU
		['atm'] = 'Fleeca',
		['atm_subtitle'] = 'ATM',
		['withdraw'] = 'Withdraw',
	    ['deposit'] = 'Deposit',
		['billings'] = '~b~Billings',
		['billings_disc'] = 'Invoices received',
		--------------------------------------
		['money_in_cash'] = '~g~Cash',
		['money_in_bank'] = '~o~Balance',
		----------------------------------------
		['rob'] = '~r~Rob',
		['rob2'] = 'Rob',
		['rob_disc'] = '~r~Rob the ATM!',
		['rob_disc_item'] = '~o~Are you sure you want to do this?',
		['stop'] = '~r~Cancel',
		['yes'] = '~g~Yes',
		['error'] = 'Error',
		['atm_blip'] = 'ATM',
		----------------------------------------
		['withdraw_disc'] = 'Withdraw money from your account',
		['withdraw_disc_info_item'] = 'Withdraw money:',
		['withdraw_custom_item'] = '~g~Custom payout',
		['withdraw_custom_box'] = 'How much do you want to withdraw?',
		['deposit_disc'] = 'Deposit money into your account',
		['deposit_disc_info_item'] = 'Deposit money:',
		['deposit_custom_item'] = '~g~Custom deposit',
		['deposit_custom_box'] = 'How much do you want to deposit?',
		['login'] = 'Login',
		['logout'] = 'Logout',
		['login_disc'] = 'Access the ~b~ATM~w~!',
		['logout_disc'] = 'Log out of the ~b~ATM~w~!',
		-----
		['atm1'] = '~g~100$', -- still change like the Config.Price's are!
		['atm2'] = '~g~500$',
		['atm3'] = '~g~1 000$',
		['atm4'] = '~g~10 000$',
		-----
		['bank_notify_1'] = '~g~%s$~s~ have been withdrawn from your account',
		['bank_notify_2'] = '~r~No %s$~w~ can be withdrawn if you do not have them!',
		['bank_notify_3'] = 'There were ~g~%s$~s~ deposited in your account',
		['bank_notify_4'] = 'You can ~r~not include %s$~w~ if you do not have them!',
		----
		['welcome'] = '~b~Welcome back!',
		['welcome_player'] = 'Welcome back, ~b~%s~w~! Your Fleeca Bank LS is always at your service!',
		---- NEW in V2 ----
		['robbery_notify1'] = '~r~You start tampering with the ATM...~w~',
		['robbery_notify2'] = 'The display can be detached now, better do it fast!',
		['robbery_notify3'] = '~r~The cash box could be broken open.... The cops were notified...',
		['robbery_notify4'] = '~r~You pull out the first cash box...~w~',
		['robbery_notify5'] = 'You see the bundles and start packing them!',
		['robbery_notify6'] = 'These were ~g~$%s~w~!',
		['robbery_notify7'] = 'These were more ~g~$%s~w~!',
		['robbery_notify8'] = 'That was ~g~$%s~w~ again! Now the ATM is empty, run!',
		----
		['police_notify'] = 'An ATM reports a malfunction or forced entry!',
		['robbery_notenough'] = 'There is not enough police in Los Santos!',
		--- NEW in 2.1
		['transfer'] = 'Transfer',
		['transfer_menu_but'] = '~o~Transfer',
		['transfer_disc'] = 'Make a transfer to another player.',
		['tranfer_button'] = '~g~Do the transfer',
		['daily_costs_title'] = 'Accountmaintenancecharge',
		['daily_costs_msg'] = 'You have had ~r~$%s~w~ deducted.',
		['daily_costs_msg_failed'] = '~r~You could not afford the account maintenance fees...',
		['transfer_failed_self'] = '~r~You can not transfer money to yourself.',
		['transfer_failed_too_much'] = '~r~You can not transfer that much if you do not own it.',
		['transfer_success'] = 'You transfer ~r~$ %s~s~ to ~r~%s.',
		['transfer_received'] = 'You will receive a transfer in the amount of ~g~$ %s~s~ through ~g~%s.',
		['transfer_who_received'] = 'What is the IBAN of the recipient?',
		['transfer_amount'] = 'How much do you want to transfer?',
		['atm_rob_police_title'] = 'ATM alert',
		['atm_rob_police_disc'] = 'ATM Security System',
		['atm_rob_police_msg'] = 'An ATM machine reports suspicious activity.',
		['atm_rob_police_blip'] = 'ATM - Dispatch',
		--- advancedblips
		['times1_blip'] = 'Opening hours',
		['times2_blip'] = '5:00 AM - 10:30 PM',
		['withdraw_blip'] = 'Cash Withdrawal',
		['yes_blip'] = 'Yes',
		['sendmoney_blip'] = 'Transfers',
		['employees_blip'] = 'Employees',
		['employees_amount_blip'] = '1-2',
		['place_blip'] = 'Location',
		['place2_blip'] = 'Public Bank',
		['disc_blip'] = 'Your Fleeca Bank Los Santos is there for you at all times. Safely deposit your money & benefit from numerous advantages!',
		---- update
		['transactions_info'] = 'Transactions',
		['payback_message'] = 'You still have an outstanding credit of ~r~$%s~s~. Please repay it.',
		['payback_successfully'] = 'You have fully repaid the credit.',
		['payback_not_money'] = 'You must repay the full amount of ~g~$50,000~s~.',
		['payback_failed'] = 'You must repay the full amount of ~g~$50,000~s~.',
		['takecredit_failed'] = 'You already have an ongoing credit with this bank. Repay it to take a new one.',
		['takecredit_success'] = 'You have taken a credit of ~g~$50,000~s~.',
		['credit_info'] = 'Credit: $50,000',
		['paycredit_info'] = '~p~Pay back credit',
		['takecredit_info'] = '~p~Take credit',
		['credit'] = 'Credit',
		['credit2'] = 'Take a credit',
		['insertcard'] = 'Insert Creditcard...',
		
		--
	},
