 ['ch'] = {
        ['Togglehudon'] = 'HUD ~g~aktiviert',
        ['Togglehudoff'] = 'HUD ~r~deaktiviert',
        ['LowHunger'] = '~p~Du hesch scho e Wile nüt meh ässe... Du söttisch öppis Essbaars finde.',
        ['LowThirst'] = '~p~Du hesch scho e Wile nüt meh trinke... Du söttisch öppis Trinkbaars finde.',
        ['LowHunger2'] = '~r~Du muesch öppis ässe, dass du nid verhungerisch...',
        ['LowThirst2'] = '~r~Du muesch öppis trinke, dass du nid verdschtecksch...',
        ['SpeedDeactivated'] = '~w~Gschwindigkeitsregler~r~\nDeaktiviert',
        ['SpeedSet1'] = '~w~Gschwindigkeitsregler~g~\nAktiviert:~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Gschwindigkeitsregler~g~\nAktiviert:~w~ %s MP/H.',
        ['fl'] = 'Spraachbereich: ~g~Flüstere~w~.',
        ['no'] = 'Spraachbereich: Kurz.',
        ['br'] = 'Spraachbereich: ~o~Normal~w~.',
        ['sc'] = 'Spraachbereich: ~r~Schreie~w~.',
    },
