['de'] = {
        ['Togglehudon'] = 'Hud ~g~angeschaltet',
        ['Togglehudoff'] = 'Hud ~r~ausgeschaltet',
        ['LowHunger'] = '~p~Du hast schon eine Weile nichts mehr gegessen... Du solltest etwas essbares aufstöbern.',
        ['LowThirst'] = '~p~Du hast schon eine Weile nichts mehr getrunken... Du solltest etwas trinkbares aufstöbern.',
        ['LowHunger2'] = '~r~Du musst etwas essen um nicht zu verhungern...',
        ['LowThirst2'] = '~r~Du musst etwas trinken um nicht zu verdursten...',
        ['SpeedDeactivated'] = '~w~Tempomat~r~\nDeaktiviert',
        ['SpeedSet1'] = '~w~Tempomat~g~\nAktiviert:~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Tempomat~g~\nAktiviert:~w~ %s MP/H.',
        ['fl'] = 'Sprachbereich: ~g~Flüstern~w~.',
        ['no'] = 'Sprachbereich: Kurz.',
        ['br'] = 'Sprachbereich: ~o~Brüllen~w~.',
        ['sc'] = 'Sprachbereich: ~r~Schreien~w~.',
    },
