['en'] = {
        ['Togglehudon'] = 'Hud ~g~turned on',
        ['Togglehudoff'] = 'Hud ~r~turned off',
        ['LowHunger'] = '~p~You haven\'t eaten in a while... You should find something edible.',
        ['LowThirst'] = '~p~You haven\'t drunk anything in a while... You should find something drinkable.',
        ['LowHunger2'] = '~r~You need to eat to avoid starving...',
        ['LowThirst2'] = '~r~You need to drink to avoid dehydration...',
        ['SpeedDeactivated'] = '~w~Cruise Control~r~\nDeactivated',
        ['SpeedSet1'] = '~w~Cruise Control~g~\nActivated:~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Cruise Control~g~\nActivated:~w~ %s MP/H.',
        ['fl'] = 'Voice Range: ~g~Whisper~w~.',
        ['no'] = 'Voice Range: Short.',
        ['br'] = 'Voice Range: ~o~Normal~w~.',
        ['sc'] = 'Voice Range: ~r~Shouting~w~.',
    },
