['es'] = {
        ['Togglehudon'] = 'HUD ~g~activado',
        ['Togglehudoff'] = 'HUD ~r~desactivado',
        ['LowHunger'] = '~p~Hace un tiempo que no comes... Deberías encontrar algo para comer.',
        ['LowThirst'] = '~p~Hace un tiempo que no bebes... Deberías encontrar algo para beber.',
        ['LowHunger2'] = '~r~Debes comer para evitar morir de hambre...',
        ['LowThirst2'] = '~r~Debes beber para evitar la deshidratación...',
        ['SpeedDeactivated'] = '~w~Control de crucero~r~\nDesactivado',
        ['SpeedSet1'] = '~w~Control de crucero~g~\nActivado:~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Control de crucero~g~\nActivado:~w~ %s MP/H.',
        ['fl'] = 'Rango de voz: ~g~Susurro~w~.',
        ['no'] = 'Rango de voz: Corto.',
        ['br'] = 'Rango de voz: ~o~Normal~w~.',
        ['sc'] = 'Rango de voz: ~r~Grito~w~.',
    },
