['fr'] = {
        ['Togglehudon'] = 'HUD ~g~activé',
        ['Togglehudoff'] = 'HUD ~r~désactivé',
        ['LowHunger'] = '~p~Vous ne avez pas mangé depuis un moment... Vous devriez trouver quelque chose à manger.',
        ['LowThirst'] = '~p~Vous ne avez pas bu depuis un moment... Vous devriez trouver quelque chose à boire.',
        ['LowHunger2'] = '~r~Vous devez manger pour éviter de mourir de faim...',
        ['LowThirst2'] = '~r~Vous devez boire pour éviter la déshydratation...',
        ['SpeedDeactivated'] = '~w~Régulateur de vitesse~r~\nDésactivé',
        ['SpeedSet1'] = '~w~Régulateur de vitesse~g~\nActivé :~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Régulateur de vitesse~g~\nActivé :~w~ %s MP/H.',
        ['fl'] = 'Portée vocale : ~g~Chuchoter~w~.',
        ['no'] = 'Portée vocale : Courte.',
        ['br'] = 'Portée vocale : ~o~Normale~w~.',
        ['sc'] = 'Portée vocale : ~r~Crier~w~.',
    },
