['nl'] = { -- thanks to @adamnyc
        ['Togglehudon'] = 'HUD ~g~ingeschakeld',
        ['Togglehudoff'] = 'HUD ~r~uitgeschakeld',
        ['LowHunger'] = '~p~Je hebt een tijdje niet gegeten... Je zou iets eetbaars moeten vinden.',
        ['LowThirst'] = '~p~Je hebt een tijdje niet gedronken... Je zou iets drinkbaars moeten vinden.',
        ['LowHunger2'] = '~r~Je moet eten om niet uit te hongeren...',
        ['LowThirst2'] = '~r~Je moet drinken om uitdroging te voorkomen...',
        ['SpeedDeactivated'] = '~w~Snelheidsregelaar~r~\nUitgeschakeld',
        ['SpeedSet1'] = '~w~Snelheidsregelaar~g~\nIngeschakeld:~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Snelheidsregelaar~g~\nIngeschakeld:~w~ %s MP/H.',
        ['fl'] = 'Spraakbereik: ~g~Fluisteren~w~.',
        ['no'] = 'Spraakbereik: Kort.',
        ['br'] = 'Spraakbereik: ~o~Normaal~w~.',
        ['sc'] = 'Spraakbereik: ~r~Schreeuwen~w~.',
    },
