['pl'] = {
        ['Togglehudon'] = 'Hud ~g~włączony',
        ['Togglehudoff'] = 'Hud ~r~wyłączony',
        ['LowHunger'] = '~p~Nie jadłeś od dłuższego czasu... Powinieneś znaleźć coś do jedzenia.',
        ['LowThirst'] = '~p~Nie piłeś od dłuższego czasu... Powinieneś znaleźć coś do picia.',
        ['LowHunger2'] = '~r~Musisz coś zjeść, aby uniknąć głodu...',
        ['LowThirst2'] = '~r~Musisz coś wypić, aby uniknąć odwodnienia...',
        ['SpeedDeactivated'] = '~w~Tempomat~r~\nDezaktywowany',
        ['SpeedSet1'] = '~w~Tempomat~g~\nAktywowany:~w~ %s KM/H.',
        ['SpeedSet2'] = '~w~Tempomat~g~\nAktywowany:~w~ %s MP/H.',
        ['fl'] = 'Zasięg głosu: ~g~Szept~w~.',
        ['no'] = 'Zasięg głosu: Krótki.',
        ['br'] = 'Zasięg głosu: ~o~Normalny~w~.',
        ['sc'] = 'Zasięg głosu: ~r~Krzyk~w~.',
    },
