['tr'] = {
		['Togglehudon'] = 'Hud ~g~açıldı',
		['Togglehudoff'] = 'Hud ~r~kapatıldı',
		['LowHunger'] = '~p~Uzun süredir bir şey yemediniz... Yiyecek bir şeyler bulmalısınız.',
		['LowThirst'] = '~p~Uzun süredir bir şey içmediniz... İçilecek bir şeyler bulmalısınız.',
		['LowHunger2'] = '~r~Açlıktan ölmemek için bir şeyler yemeniz gerekiyor...',
		['LowThirst2'] = '~r~Susuzluktan ölmemek için bir şeyler içmeniz gerekiyor...',
		['SpeedDeactivated'] = '~w~Hız Sabitleyici~r~\nDevre dışı bırakıldı',
		['SpeedSet1'] = '~w~Hız Sabitleyici~g~\nAktif:~w~ %s KM/S.',
		['SpeedSet2'] = '~w~Hız Sabitleyici~g~\nAktif:~w~ %s MP/S.',
		['fl'] = 'Ses Aralığı: ~g~Fısıltı~w~.',
		['no'] = 'Ses Aralığı: Kısa.',
		['br'] = 'Ses Aralığı: ~o~Normal~w~.',
		['sc'] = 'Ses Aralığı: ~r~Bağırma~w~.',
	},
